export const WORDS: string[] = [
  "APPLE","BAND","BANK","BEACH","BELL","BOLT","BOND","BOOM","BRIDGE","BUGLE",
  "CAPITAL","CARD","CHAIR","CHEST","CIRCLE","CLOAK","COMPOUND","CRANE","DANCE","DIAMOND",
  "DRAGON","DRESS","EAGLE","FIELD","FIGURE","FILM","FORCE","GIANT","GLASS","GOLD",
  "GRACE","GREEN","GROUND","HAND","HEART","HORN","JACK","KING","KNIGHT","LAB",
  "LEAD","LEMON","LINK","LOCK","MARBLE","MASS","MINT","MOON","NIGHT","NOTE",
  "NURSE","ORANGE","PALM","PARK","PILOT","PIT","PLATE","POINT","QUEEN","RING",
  "ROCK","ROOT","SCALE","SHADOW","SHIP","SLIP","SNOW","SPACE","SPRING","STAR",
  "STATE","STICK","STRAW","TABLE","THUMB","TICK","TRIP","VACUUM","WAVE","WELL",
];
